### ISSUE TITLE
Darkmode for the frontend

### ISSUE THREAD

**Issue by Restioson** [SADiLaR/term_platform#180]
It would be nice to have a darkmode version of the public frontend (not the admin backend). We could also obey the browser's default colourscheme settings (I believe this is exposed to CSS).

**Comment by friedelwolff** [comment]
The admin backend actually already supports dark mode - a feature inherited from Django, but with some customisations we did to make it work with our colour scheme. It isn't bug-free, but it is usable.
I have an untested stash that might get someone going:
```CSS
/*
@media (prefers-color-scheme: dark) {
*/
[data-bs-theme="dark"] {
    :root {
       --primary: red; /*#1a2f69;*/
       --sdlr-red: #d11f26;
       --bs-primary: var(--primary);
       --bs-primary-rgb: 26, 47, 105; {# identical to --primary #}
       --bs-blue: var(--primary);
    }
    .btn-primary {
        --bs-btn-bg: var(--primary);
        --bs-btn-border-color: var(--primary);
        --bs-btn-disabled-bg: var(--primary);
    }
    .card {
       --bs-card-border-color: var(--sdlr-red);
    }
    .nav-pills {
        --bs-nav-pills-link-active-bg: var(--bs-primary);
        --bs-navbar-active-color: #fff;
    }
}
```
What we see from the Django back-end, is the idea of a tri-state switcher (light, dark, auto==browser setting). Might be worth considering, probably reusing the same storage so that both switchers (frontend and backend) complement each other.
